set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic) # use dynamic CRT; that's how all our other static libs are.
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_SYSTEM_NAME windows)

set(VCPKG_C_FLAGS_DEBUG "/D_ITERATOR_DEBUG_LEVEL=2")
set(VCPKG_CXX_FLAGS_DEBUG "/D_ITERATOR_DEBUG_LEVEL=2")

set(VCPKG_C_FLAGS_RELEASE "/D_ITERATOR_DEBUG_LEVEL=0")
set(VCPKG_CXX_FLAGS_RELEASE "/D_ITERATOR_DEBUG_LEVEL=0")

